apiVersion: apps/v1
kind: Deployment
metadata:
  name:  violin-app
  labels:
    name: violin-app
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: violin-app
  template:
    metadata:
      labels:
        name:  violin-app
    spec:
      containers:
      - image:  ahmedgrati/goviolin
        name:  violin-container
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
      restartPolicy: Always